/**
  * tb_payments.
  *
  * @author cvaldezissc
  * @purpose Be the history of payments per user
  */

USE `rpay`;

DROP TABLE IF EXISTS `rpay`.`tb_paymentsoractions`;

CREATE TABLE `tb_paymentsoractions`
(
  `id`                INT(11)       NOT NULL AUTO_INCREMENT               COMMENT 'Unique identifier of the payment'
  , `user_id`         INT(11)       NOT NULL DEFAULT 0                    COMMENT 'Identifies the user that makes the purchase'
  , `pack_id`         INT(11)       NOT NULL DEFAULT 0                    COMMENT 'Identifies the set of actions that will be purchased defined in the packs table'
  , `sent_amount`     DECIMAL(29,9) NOT NULL DEFAULT 1.0                  COMMENT 'Paid price'
  , `reference`       VARCHAR(200)  NOT NULL DEFAULT ''                   COMMENT 'This is the reference that will be generated by the payments processor'
  , `sent_comment`    VARCHAR(200)      NULL DEFAULT ''                   COMMENT 'If needed the user can leave a comment for the future, '
  , `creation_date`     DATETIME 	NOT NULL DEFAULT CURRENT_TIMESTAMP    COMMENT 'When was the payment tried'
  , `status`            TINYINT(4)  NOT NULL DEFAULT '1'                  COMMENT 'Which is going to be the last status (Paid Successful, With error, etc)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_UNIQUE` (`reference`),
  KEY `ix_payments_01` (`user_id`, `pack_id`),
  KEY `ix_payments_02` (`sent_amount`),
  KEY `ix_payments_03` (`status`)
)
ENGINE=InnoDB
AUTO_INCREMENT=1
DEFAULT CHARSET=latin1;


